// Textos de respaldo de Respuestas y Plantillas.
//
// Se usan cuando Google Sheets no responde (sin red, 404 transitorio de Apps
// Script, pestaña vacía): los agentes nunca se quedan sin respuestas. Cuando el
// Sheet responde, SUS filas reemplazan a estas.
//
// Son una foto del Sheet: si cambias mucho los textos allí, conviene
// actualizar este archivo de vez en cuando (ver README, "Respaldo").
//
// Tokens de texto plano (ver CLAUDE.md):
//   nombreAgente      -> nombre del agente (o "un agente")
//   holaCliente       -> "Hola Juan," o "Hola,"
//   encabezadoCliente -> "Hola Juan 👋" + salto de línea; si no hay cliente se omite (escríbelo
//                        solo, en su propia línea, antes del texto)
//   saludoHora        -> "buen día" | "buenas tardes" | "buenas noches"
//   SaludoHora        -> igual, con mayúscula inicial

const RESPUESTAS_DEFAULT = [
  {"id":"daysMessage","categoria":"Saludos","titulo":"Saludo","texto":"holaCliente muy saludoHora, ¿cómo estás? Hablas con nombreAgente, del equipo soporte Lizto ☑︎."},
  {"id":"falloSistema","categoria":"Incidencias","titulo":"Fallo del sistema","texto":"holaCliente muy saludoHora, ¿cómo estás? Hablas con nombreAgente, del equipo soporte Lizto ☑︎. ¿Tienes disponibilidad en este momento para que nos conectemos y revisarlo contigo? Así podemos ayudarte de forma más rápida. En caso de que no sea posible, puedes compartirnos por favor imágenes o un video del inconveniente para poder validarlo en detalle. Quedamos atentos."},
  {"id":"modulosCapacitaciones","categoria":"Capacitaciones","titulo":"Módulos y capacitaciones","texto":"encabezadoCliente\nSaludoHora, ¿Cómo estás? Hablas con nombreAgente del equipo de soporte de Lizto ☑. Cuéntanos por favor qué módulo o proceso deseas revisar y te apoyamos por este medio paso a paso para resolver tus dudas.\n\nTambién contamos con espacios grupales donde explicamos módulos específicos y resolvemos preguntas en vivo:\n\nCapacitaciones por módulos:\nMartes – 9:00 a.m.\n\nEspacios de resolución de dudas generales:\nMartes – 5:00 p.m.\nJueves – 9:00 a.m. y 5:00 p.m.\n\nLink 9 am: https://us06web.zoom.us/j/83345602567\nLink 5 pm: https://us06web.zoom.us/j/83272928783?pwd=5oyn4FfSuZ7F5gPDakoUUqVqhTmKbT.1\n\nSi después de ayudarte con tu caso por este medio sientes que es necesario un acompañamiento más personalizado, con gusto podemos agendar una reunión."},
  {"id":"validarPagoMessage","categoria":"Pagos","titulo":"Confirmación de pago","texto":"encabezadoCliente\n¡Mil gracias por el pago! Puedes seguir haciendo uso del sistema con normalidad 😁"},
  {"id":"pagoGraciasMessage","categoria":"Pagos","titulo":"Solicitar link de pago","texto":"encabezadoCliente\nMe puedes indicar por favor el número de NIT del negocio para validar con el área contable 😊"},
  {"id":"solicitarLinkMessage","categoria":"Pagos","titulo":"Solicitar comprobante","texto":"encabezadoCliente\nSaludoHora, ¿cómo estás? hablas con nombreAgente del equipo de soporte de Lizto ☑︎. Lo sentimos, el sistema suspendió el servicio por falta de pago. Por favor, envíanos el comprobante de pago y el NIT para reactivarlo"},
  {"id":"demorasDIAN","categoria":"Incidencias","titulo":"Demoras DIAN","texto":"encabezadoCliente\n¿Cómo estás? hablas con nombreAgente del equipo de soporte de Lizto ☑︎. Actualmente la DIAN se encuentra presentando demoras en la generación de las facturas electrónicas, no te preocupes, puedes verificar más tarde si las facturas ya se encuentran generadas 😀"},
  {"id":"casoEscalado","categoria":"Escalamiento","titulo":"Caso escalado","texto":"Te confirmo que ya hemos escalado tu caso a nuestro equipo especializado para que puedan ayudarnos lo más pronto posible. En cuanto tengamos una respuesta concreta, nos comunicaremos contigo para informarte sobre ello. Agradecemos tu paciencia y comprensión mientras trabajamos en la solución de tu caso 😊"},
  {"id":"algoMas","categoria":"Cierre","titulo":"Pregunta final","texto":"Con mucho gusto, ¿la solución brindada fue de ayuda para ti? 😁"},
  {"id":"despedidaMessage","categoria":"Cierre","titulo":"Despedida","texto":"Ha sido un placer ayudarte. Si necesitas más ayuda no dudes en contactarnos. ¡Te deseo un excelente día! 😉\n\nTe dejamos una encuesta de satisfacción para que puedas calificar nuestra atención: short.lizto.co/pkFN2dEfvu"},
  {"id":"cierreSinRespuesta","categoria":"Cierre","titulo":"Cierre sin respuesta","texto":"¡Hola! 🖐️ No queremos ser molestos, solo queríamos confirmar si pudiste resolver tu duda o si aún necesitas ayuda con la plataforma. Si estás ocupado(a), no te preocupes, cuando tengas un espacio nos escribes y reanudamos la atención."},
  {"id":"calificacion","categoria":"Cierre","titulo":"Calificación","texto":"¿Qué tan satisfecho estás con tu experiencia general utilizando el sistema y la atención recibida?\n[ 1 ] ⭐ Muy insatisfecho\n[ 2 ] ⭐⭐ Insatisfecho\n[ 3 ] ⭐⭐⭐ Neutral\n[ 4 ] ⭐⭐⭐⭐ Satisfecho\n[ 5 ] ⭐⭐⭐⭐⭐ Muy satisfecho\n¡Agradecemos mucho tu tiempo! 🙌"}
];

const PLANTILLAS_DEFAULT = [
  {"id":"facturacionElectronica","categoria":"Facturación","titulo":"Facturación electrónica","texto":"Para integrar la facturación electrónica en la cuenta es necesario que nos envíes un correo con la solicitud, en este deben adjuntar 3 archivos: \n1. RUT actualizado para verificar la información en la cuenta. \n2. Set de pruebas. Este lo recibes cuando te habilitas para facturar electrónicamente desde la DIAN \n\nCómo habilitarse\nhttps://liztosoftware.zohodesk.com/portal/es/kb/articles/habilitaci%C3%B3n-de-facturaci%C3%B3n-electr%C3%B3nica-5-7-2024 \n\nConfigurar modos de operación con SOLUCIONES ALEGRA SAS \nhttps://liztosoftware.zohodesk.com/portal/es/kb/articles/proceso-de-habilitaci%C3%B3n-facturaci%C3%B3n-electr%C3%B3nica-paso-1-5-22-4-2025 \n\nSet de pruebas \nhttps://liztosoftware.zohodesk.com/portal/es/kb/articles/proceso-de-habilitaci%C3%B3n-facturaci%C3%B3n-electr%C3%B3nica-paso-3-53 \n\n 3. Archivo de la resolución para facturación electrónica que también solicitan desde el portal de la DIAN \n\nSolicitar resolución \nhttps://liztosoftware.zohodesk.com/portal/es/kb/articles/proceso-de-habilitaci%C3%B3n-facturaci%C3%B3n-electr%C3%B3nica-paso-5-5 \n\nAsociar prefijos con SOLUCIONES ALEGRA SAS o Alegra \nhttps://liztosoftware.zohodesk.com/portal/es/kb/articles/proceso-de-habilitaci%C3%B3n-facturaci%C3%B3n-electr%C3%B3nica-paso-4-5 \n\nSi tienes alguna duda con el proceso, te compartimos un paso a paso de cómo realizar el proceso: \nhttps://liztosoftware.zohodesk.com/portal/es/kb/articles/proceso-de-habilitaci%C3%B3n-facturaci%C3%B3n-electr%C3%B3nica-clase-grupal-24-02-2026"},
  {"id":"nominaElectronica","categoria":"Facturación","titulo":"Nómina electrónica","texto":"La nómina electrónica es uno de los documentos digitales que puedes gestionar a través de Lizto. Este proceso está regulado por la DIAN y permite emitir o respaldar electrónicamente los pagos de salario a tus empleados. Para utilizar la nómina electrónica en Lizto, es necesario contratar un plan de facturación electrónica que incluya el módulo de Nómina Electrónica, actualmente este tiene un valor de $30,900 COP mensuales."},
  {"id":"apiWhatsapp","categoria":"WhatsApp","titulo":"API WhatsApp","texto":"Si deseas integrar el API de WhatsApp con Lizto, es importante que tengas en cuenta que este proceso se realiza directamente con Meta (Facebook), y requiere cumplir ciertos requisitos para garantizar la autenticidad y seguridad del negocio.\nAquí te comparto los puntos más importantes:\n\n1. Fanpage activa: Debes contar con una página de Facebook para tu negocio, que tenga actividad e interacciones reales (por ejemplo: publicaciones, comentarios, likes, reseñas).\n\n 2. Dominio web propio: Se recomienda tener un sitio web con un dominio que represente el nombre de tu negocio (por ejemplo: www.tusalon.com), ya que esto facilita la verificación del negocio ante Meta.\n\n 3. Documentos legales: Meta pedirá validar los datos legales del negocio, por lo que debes contar con documentos como el RUT, Cámara de Comercio o equivalente, donde el nombre coincida con el registrado en tu cuenta empresarial de Facebook.\n\n 4. Número exclusivo para el API: El número de WhatsApp que vas a usar en la integración no debe estar vinculado a ninguna cuenta de WhatsApp (ni personal ni Business). Este número se asociará únicamente al canal de mensajería empresarial y no podrá usarse de forma tradicional una vez quede vinculado.\n\n 5. Capacidad de recibir llamadas o SMS: El número debe poder recibir llamadas o mensajes de texto para completar la verificación con código.\n\nSi cumples con estos puntos, podemos ayudarte a iniciar el proceso junto con nuestro equipo de soporte. Una vez aprobado, podrás enviar notificaciones a tus clientes por WhatsApp de forma automática desde Lizto."},
  {"id":"whatsappLITE","categoria":"WhatsApp","titulo":"WhatsApp LITE","texto":"Antes de comenzar, te comparto los requisitos indispensables.\n\nPara poder completar la conexión necesitas, sí o sí, tener listo lo siguiente:\n\n-Una cuenta de Facebook y acceso a ella (usuario y contraseña a la mano).\n-Una fanpage (página) de Facebook, o los permisos necesarios para poder crearla en el momento de registrar el número. Si aún no la tienes, en el mismo proceso de conexión te permite crearla de forma fácil y rápida.\n-El número de teléfono que vas a conectar ya debe estar registrado en WhatsApp Business (la app oficial); es decir, debe funcionar hoy como una cuenta de WhatsApp Business antes de iniciar este proceso.\n-La persona que hace la integración debe iniciar sesión en Facebook desde el computador con una sesión distinta a la del celular que tiene WhatsApp Business, ya que ese celular debe quedar libre para leer y escanear el código QR que aparece en pantalla."},
  {"id":"solicitudCorreo","categoria":"Solicitudes por correo","titulo":"Solicitud correo","texto":"Por medio del correo (ayuda@soportelizto.co) debes enviarnos la solicitud correspondiente y adicional adjuntar los siguientes datos:\n\nNombre comercial del negocio: \nNIT: \nNombre del contacto: \nNombre de la sede (En caso de que cuentes con más de una sede, es importante que nos indiques a cuál de ellas corresponde la solicitud)\n\nEn el asunto del correo por favor indica: Solicitud [motivo de la solicitud]\n\nEjemplo: Solicitud modificación de datos."},
  {"id":"solicitudRecuperarEspecialista","categoria":"Solicitudes por correo","titulo":"Solicitud recuperar especialista","texto":"Por medio del correo (ayuda@soportelizto.co) debes enviarnos la solicitud correspondiente y adicional adjuntar los siguientes datos: \n\nNombre comercial del negocio: \nNIT: \nNombre del contacto: \nNombre del especialista eliminado: \nCorreo electrónico del especialista: \nNombre de la sede (En caso de que cuentes con más de una sede, es importante que nos indiques a cuál de ellas corresponde la solicitud)\n\nEn el asunto del correo por favor indica: Solicitud recuperar especialista [nombre del negocio]"},
  {"id":"solicitudCambioRazonSocial","categoria":"Solicitudes por correo","titulo":"Solicitud cambio de razón social","texto":"Por medio del correo (ayuda@soportelizto.co) debes enviarnos la solicitud correspondiente y adicional adjuntar los siguientes datos: \n\nNIT: \nRazón social actual: \nNueva razón social (nombre, identificación y demás datos necesarios): \nNombre de la sede (En caso de que cuentes con más de una sede, es importante que nos indiques a cuál de ellas corresponde la solicitud) \nArchivo adjunto de la nueva razón social \n\nEn el asunto del correo por favor indica: Solicitud cambio de razón social [nombre del negocio]"},
  {"id":"solicitudIdSetPruebas","categoria":"Facturación","titulo":"Plantilla solicitud ID Set Pruebas","texto":"SaludoHora.\n\nCordial saludo.\n\nMe comunico con ustedes ya que actualmente utilizamos **Soluciones Alegra SAS** como proveedor tecnológico para la facturación electrónica y requerimos conocer el **código del Set de Pruebas** asociado a nuestra empresa, debido a que este ya fue aceptado por la DIAN y no es posible visualizarlo nuevamente desde el portal.\n\nA continuación, compartimos los datos de la empresa para facilitar la validación:\n\n* **Razón social:**\n* **NIT:**\n* **Nombre del establecimiento (si aplica):**\n* **Correo electrónico registrado:**\n* **Nombre de la persona de contacto:**\n* **Teléfono de contacto:**\n\nAgradecemos su colaboración compartiéndonos el código del Set de Pruebas o la información necesaria para continuar con el proceso.\n\nQuedamos atentos a su respuesta.\n\nMuchas gracias."}
];
